/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ai.improve.android;

import org.junit.Test;

import java.util.Arrays;
import java.util.logging.Logger;

import static org.mockserver.model.HttpRequest.request;
import static org.mockserver.model.HttpResponse.response;

//@RunWith(RobolectricTestRunner.class)
public class SimpleTest {
    private static final Logger jul = Logger.getLogger(ImproveTrackerTest.class.getName());


    public SimpleTest() {
    }

    @Test
    public void initMockServer() {
        jul.severe("SEVERE");
        jul.info("INFO");
        jul.fine("FINE");
        jul.finer("FINER");
        jul.finest("FINEST");

        Object x = new int[10];

        System.out.println(Arrays.asList(x).get(0));
    }
}
